## ControlSwap Configuration
## Runner-only, one-at-a-time control swap challenge

# Teams Configuration
teams:
  runners: []  # List of runner player names

# Swap System Configuration
swap:
  # Fixed interval or random swap with Gaussian jitter
  randomize: false
  # Base interval in seconds (or mean if randomized)
  interval: 60
  # Min and max interval in seconds (only used if randomize is true)
  min_interval: 30
  max_interval: 90
  # Jitter settings (only used if randomize is true)
  jitter:
    # Standard deviation in seconds
    stddev: 15
    # Whether to clamp within min/max limits
    clamp: true
  # Grace period after swaps (in ticks, 20 ticks = 1 second)
  grace_period_ticks: 40
  # Auto-pause if a runner disconnects
  pause_on_disconnect: true
  # If true, apply the final active runner's state to all runners when ending the game
  preserve_runner_progress_on_end: false

# Safe Swap Configuration
safe_swap:
  # Whether to enable safe swap feature
  enabled: false
  # Horizontal scan radius (blocks)
  horizontal_radius: 5
  # Vertical scan distance (blocks)
  vertical_distance: 10
  # Dangerous blocks to avoid (material names)
  dangerous_blocks:
    - LAVA
    - MAGMA_BLOCK
    - CACTUS
    - CAMPFIRE
    - FIRE
    - SOUL_FIRE
    - SOUL_CAMPFIRE
    - POINTED_DRIPSTONE

# Freeze Mode for Inactive Runners
# Options: EFFECTS, SPECTATOR, LIMBO, CAGE
freeze_mode: CAGE

# Limbo configuration
limbo:
  world: "world"
  x: 0.5
  y: 200.0
  z: 0.5

# Movement and Interaction Control
cancel:
  # Cancel movement for inactive runners
  movement: true
  # Cancel interactions for inactive runners
  interactions: true

## Note: No hunters, no compasses — tracking removed

# GUI Configuration
gui:
  main_menu:
    title: "ControlSwap Menu"
    rows: 3
  team_selector:
    title: "Runner Selector"
    rows: 4
  settings:
    title: "Settings"
    rows: 5

# Broadcast Configuration
broadcasts:
  # Whether to broadcast swap events to all players
  enabled: true
  # Whether to broadcast game start/stop events
  game_events: true
  # Whether to broadcast team changes
  team_changes: true

# Freeze Mechanic Configuration
freeze_mechanic:
  enabled: false
  duration_ticks: 100  # 5 seconds
  check_interval_ticks: 20
  max_distance: 50

# Timer Visibility Configuration
timer_visibility:
  # Whether active runners see the timer
  runner_visibility: "last_10"  # Options: "always", "last_10", "never"
  # Whether waiting runners see the timer
  waiting_visibility: "always"  # Options: "always", "last_10", "never"

## Voice chat integration removed in ControlSwap

## Power-ups removed in ControlSwap

## Last Stand removed in ControlSwap

## Kits removed in ControlSwap

## Stats removed in ControlSwap

## World border control removed in ControlSwap

## Bounty system removed in ControlSwap

## Sudden death removed in ControlSwap

# Donation / Support
donation:
  # URL used for the clickable donate message shown when the game ends
  url: "https://donate.stripe.com/8x29AT0H58K03judnR0Ba01"
