name: ControlSwap
version: '1.2'
main: com.example.speedrunnerswap.SpeedrunnerSwap
api-version: '1.21'
authors: [muj3b]
description: |
  One-character, many-players challenge: only one runner controls the shared
  player at a time; control swaps on a timer. No hunters.
website: https://example.com/controlswap

commands:
  swap:
    description: Main command for ControlSwap plugin
    usage: /<command> [start|stop|pause|resume|status|shuffle|maker|setrunners|reload|clearteams]
    permission: controlswap.command
    
permissions:
  controlswap.command:
    description: Allows use of all ControlSwap commands
    default: op
  controlswap.admin:
    description: Allows administration of ControlSwap
    default: op
    children:
      controlswap.command: true
