# SpeedrunnerSwap Configuration
# Version 2.3.0

# Teams Configuration
teams:
  runners: []  # List of runner player names
  hunters: []  # List of hunter player names

# Swap System Configuration
swap:
  # Fixed interval or random swap with Gaussian jitter
  randomize: true
  # Base interval in seconds (or mean if randomized)
  interval: 60
  # Min and max interval in seconds (only used if randomize is true)
  min_interval: 30
  max_interval: 90
  # Jitter settings (only used if randomize is true)
  jitter:
    # Standard deviation in seconds
    stddev: 15
    # Whether to clamp within min/max limits
    clamp: true
  # Grace period after swaps (in ticks, 20 ticks = 1 second)
  grace_period_ticks: 40
  # Auto-pause if a runner disconnects
  pause_on_disconnect: true
  hunter_swap:
    enabled: true
    interval: 60
  hot_potato_mode:
    enabled: false

# Safe Swap Configuration
safe_swap:
  # Whether to enable safe swap feature
  enabled: true
  # Horizontal scan radius (blocks)
  horizontal_radius: 5
  # Vertical scan distance (blocks)
  vertical_distance: 10
  # Dangerous blocks to avoid (material names)
  dangerous_blocks:
    - LAVA
    - MAGMA_BLOCK
    - CACTUS
    - CAMPFIRE
    - FIRE
    - SOUL_FIRE
    - SOUL_CAMPFIRE
    - POINTED_DRIPSTONE

# Freeze Mode for Inactive Runners
# Options: EFFECTS, SPECTATOR, LIMBO
freeze_mode: LIMBO

# Limbo configuration
limbo:
  world: "world"
  x: 0.5
  y: 200.0
  z: 0.5

# Movement and Interaction Control
cancel:
  # Cancel movement for inactive runners
  movement: true
  # Cancel interactions for inactive runners
  interactions: true

# Tracker Configuration
tracker:
  # Whether to enable the compass tracker
  enabled: true
  # How often to update the compass (in ticks, 20 ticks = 1 second)
  update_ticks: 20
  # Whether to show coordinates in action bar for hunters
  show_coordinates: true
  # Particle trail for active runner
  particle_trail:
    enabled: true
    type: DUST
    # For DUST, specify color as RGB (0-255)
    color: 255,0,0
    # How often to spawn particles (in ticks)
    spawn_interval: 10
    compass_jamming:
      enabled: true
      duration_ticks: 100 # 5 seconds

# GUI Configuration
gui:
  main_menu:
    title: "SpeedrunnerSwap Menu"
    rows: 3
  team_selector:
    title: "Team Selector"
    rows: 4
  settings:
    title: "Settings"
    rows: 5

# Broadcast Configuration
broadcasts:
  # Whether to broadcast swap events to all players
  enabled: true
  # Whether to broadcast game start/stop events
  game_events: true
  # Whether to broadcast team changes
  team_changes: true

# Freeze Mechanic Configuration
freeze_mechanic:
  enabled: true
  duration_ticks: 100  # 5 seconds
  check_interval_ticks: 20
  max_distance: 50

# Timer Visibility Configuration
timer_visibility:
  # Whether active runners see the timer
  runner_visibility: "last_10"  # Options: "always", "last_10", "never"
  # Whether waiting runners see the timer
  waiting_visibility: "always"  # Options: "always", "last_10", "never"
  # Whether hunters see the timer
  hunter_visibility: "never"    # Options: "always", "last_10", "never"

# Simple Voice Chat Integration (if available)
voice_chat:
  # Whether to integrate with Simple Voice Chat
  enabled: true
  # Whether to mute inactive runners
  mute_inactive_runners: true

# Power-ups Configuration
power_ups:
  enabled: true
  good_effects:
    - SPEED
    - DOLPHINS_GRACE
    - REGENERATION
    - NIGHT_VISION
    - ABSORPTION
  bad_effects:
    - SLOWNESS
    - WEAKNESS
    - HUNGER
    - DARKNESS
    - GLOWING

# Last Stand Configuration
last_stand:
  enabled: true
  duration_ticks: 600 # 30 seconds
  strength_amplifier: 1
  speed_amplifier: 1

# Kits Configuration
kits:
  enabled: true

# Advanced Stats Configuration
stats:
  enabled: true
  # How often to update distance traveled (in ticks)
  distance_update_ticks: 20
  # Whether to display stats periodically during the game
  periodic_display: false
  periodic_display_interval: 300 # 5 minutes

# World Border Configuration
world_border:
  enabled: true
  initial_size: 2000
  final_size: 100
  # Time in seconds for the border to shrink
  shrink_duration: 1800 # 30 minutes
  warning_distance: 50
  # How often to display border warnings (in seconds)
  warning_interval: 300 # 5 minutes

# Bounty System Configuration
bounty:
  enabled: true
  # Minimum time between bounties (in seconds)
  cooldown: 300
  # Duration of the glowing effect on the target (in seconds)
  glow_duration: 300
  # Rewards for successful bounty completion
  rewards:
    strength_duration: 300 # 5 minutes
    speed_duration: 300 # 5 minutes

# Sudden Death Configuration
sudden_death:
  enabled: true
  # Time before sudden death activates (in seconds)
  activation_delay: 1200 # 20 minutes
  # Effects given to players in sudden death
  effects:
    resistance_duration: 200
    regeneration_duration: 200
  # Coordinates for the sudden death arena in The End
  arena:
    x: 100
    y: 50
    z: 0

# Compass Jamming Configuration
tracker:
  compass_jamming:
    enabled: true
    # Duration of compass jamming in ticks (20 ticks = 1 second)
    duration_ticks: 100
    # Maximum distance for random compass pointing when jammed
    max_jam_distance: 100
  runner_kit:
    - DIAMOND_SWORD 1
    - COOKED_BEEF 64
  hunter_kit:
    - IRON_SWORD 1
    - BOW 1
    - ARROW 64
